name: Removendo pastas duplicadas

on:
  push:
    branches:
      - main

jobs:
  limpeza:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Configurar identidade do Git
      run: |
        git config user.email "thiagosgentil@gmail.com"
        git config user.name "Tgetil"

    - name: Remover pastas co nomes em minusculo
      run: |
        # Lista dos diretórios para remover
        DIRS=("asaas ip s.a" "banco bs2 s.a" "banco btg pacutal" "banco c6 s.a" "banco da amazônia s.a" "banco daycoval"
              "banco do estado do espirito santo" "banco do estado do para" "banco do estado do sergipe" 
              "banco do nordeste do brasil s.a" "banco industrial do brasil s.a" "banco mercantil do brasil s.a"
              "banco original s.a" "banco pine" "banco rendimento" "banco safra s.a" "banco sofisa"
              "banco topazio" "banco triângulo - tribanco" "bancos escuros" "bank of america" "banrisul"
              "brb - banco de brasilia" "capitual" "conta simples soluções em pagamentos" "credisis"
              "cresol" "efí - gerencianet" "grafeno" "lets bank s.a" "mercado pago" "nu pagamentos s.a"
              "omie.cash" "sicoob" "sicredi" "stone pagamentos s.a")
        
        # Percorrer a lista e deletar os diretórios
        for DIR in "${DIRS[@]}"; do
          rm -rf "$DIR"
          git rm -r "$DIR"
        done

        # Se houver mudanças, commitar e dar push
        if [[ $(git status -s) ]]; then
          git commit -am "Removidas pastas duplicadas"
          git push
        fi
